### ISSUE TITLE
Local test

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/starcounter-layout-html-editor#15]
How can `starcounter-layout-html-editor` be tested locally?

Am I doing something wrong here (couldn't find any idand that's why I used `starcounter-include`)? Didn't want to change the source code of anything on the idea that since it has a demo, it should work without making any impact on the code after `bower install` + `polyserve` .

Thanks in advance!

I need it for https://github.com/Starcounter/RebelsLounge/issues/140

LE: there is only one slot: "defined-slot-name", but nothing happens when I try to "pick" it.

@tomalec , could you please give me some indications here?

![starcounter-include](https://user-images.githubusercontent.com/8951553/28872147-2e933232-7788-11e7-85c1-6043ed321d76.gif)

**Comment by Mihaiii** [comment]
Closing as not needed anymore.

**Comment by tomalec** [comment]
You should be able to move selected slot and any other element, hide it etc., also you should be able to use the ace editor to change the elements shadow DOM.
![editor](https://user-images.githubusercontent.com/17435/28980293-8e1094d6-794d-11e7-8fe5-dcdfe9f0485e.gif)


To test saving layouts you need to have working serverside, but this is a manner of yet another fix, to fully support Palindrom flow, so editor will just change the model and the propagation will be done by Palindrom.
