### ISSUE TITLE
🤸 Provide easier to use drop-down (or combo-box) for selecting composition containers

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-layout-html-editor#23]
Right now it is super hard to guess what is the purpose of each item in the list of composition containers:

![image](https://user-images.githubusercontent.com/566463/36477187-9224f9b2-1700-11e8-9490-d96f22a490f9.png)

@tomalec what can be done to improve that?

**Comment by tomalec** [comment]
It's rather UX than technical question.

I don't think the solution should be "easier drop-down".

I believe we need a completely new way to pick a view insertion point/ composition container. Back in the days we have this tree view to pick, maybe we could get it back? For sure picker like for dev tools would be handy, then we would also need bread crumnbs to select parent containers.

> what is the purpose

The purpose of all of them is the same: insert a partial view with a composition.

BTW, this dropdown was initially and still is just an input to provide any CSS selector for `<starcounter-include>`. I think the fact dropdown shows just `"slot=...,slot=..."  makes it really confusing, and let some folks to call `starcounter-include`s "slots".

I think we should ask actual users from @Starcounter/sc-apps How do you imagine picking/selecting a view insertion point?

**Comment by warpech** [comment]
First, I would like to come up with a solution that is doable before the March demo (hence the 🤸 icon in the title)

Based on what you said, I think it can be greatly improved in a quite simple way:

1. Provide a fuller CSS selector in each line, including `starcounter-include`
2. For each `s-i`, provide the HTML of the current main view
3. Use indentation to render the items in a tree-like structure

A wireframe of what I mean:

![image](https://user-images.githubusercontent.com/566463/36480341-44f1fea4-170c-11e8-9ec0-142a2e6ca067.png)

This can be achieved by https://vaadin.com/elements/vaadin-combo-box

> I think we should ask actual users from @Starcounter/sc-apps How do you imagine picking/selecting a view insertion point?

At this point I suppose they don't imagine much, because they are still not sure what is happening there. 

I want the UI to be self-descriptory, so that anyone who uses can learn the basics from it. Then we can expect improvement suggestions.

**Comment by kegor** [comment]
The first step is ready, native input-list was replaced by vaadin-combo-box:
![partial_picker_on_vaadincombobox](https://user-images.githubusercontent.com/17431807/36890097-b207efb4-1e0d-11e8-891b-bdf3f660ca42.gif)

**Comment by kegor** [comment]
Closed because fixes were merged in #25.
