### ISSUE TITLE
CSS selector dropdown should not suggest starcounter-includes that don't have `compositionprovider.Composition$` in the view-model

### ISSUE THREAD

**Issue by kegor** [Starcounter/starcounter-layout-html-editor#24]
### Steps to reproduce
https://github.com/Starcounter/Blending/issues/30#issuecomment-368865131

### Expected result
There are no exceptions while editing the composition body.

### Actual result
There is exception in dev-tools console after saving some of edited compositions:
![image](https://user-images.githubusercontent.com/17431807/36737495-3ab1c12e-1bec-11e8-8086-aaf8acb5f359.png)
— with change in [this PR](https://github.com/Starcounter/Blending/pull/97).

### Technical information
The problem is that none of the BlendingProvider_* responses at this level in JSON has Composition$.

![image](https://user-images.githubusercontent.com/17431807/36736899-c0614d32-1bea-11e8-9aef-b418b1f8be3d.png)

This level in JSON is provided by ViewKeeper for caching reasons. It cannot have compositions of its own.

The blending point starcounter-include[slot="blendingeditor/Main"] should not even be presented in the composition editor dropdown, because the view-model at this level does not have a composition provider (= does not have a BlendingProvider_* subtree with Composition$ property).

##### Starcounter version
2.4.0.5100

##### Involved apps' version
 - BlendingProvider@6.0.0
 - BlendingEditor@6.0.0

##### Browsers affected
- [x] Chrome
- [x] Firefox

**Comment by warpech** [comment]
Let's freeze that until https://github.com/Starcounter/Blending/issues/30#issuecomment-369301653 is answered.

**Comment by alshakero** [comment]
Addressed in https://github.com/Starcounter/Blending/pull/205/commits/8ece492c9edb588238df918573fa90635c4a3293

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/Blending/pull/205
