### ISSUE TITLE
Add a format button to make editing HTML easier

### ISSUE THREAD

**Issue by alshakero** [Starcounter/starcounter-layout-html-editor#43]
Maybe use Prettier https://prettier.io/docs/en/browser.html#usage

It would make life much easier.

Maybe even consider using [VS Code](https://github.com/CompuIves/codesandbox-client). That would be super cool to do after Omni.

**Comment by tomalec** [comment]
To make is quick, we can add a beautify to ace editor https://stackoverflow.com/questions/31767051/how-do-i-use-beautify-in-ace-editor

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/starcounter-layout-html-editor/commit/4c4159e086ea77fe095d1451835d25e786a34668
