### ISSUE TITLE
Lessons learned and enhancement suggestions

### ISSUE THREAD

**Issue by alshakero** [Starcounter/starcounter-layout-html-editor#44]
1. A <kbd>Format</kbd> button is needed for the DevX. Now when you add a `div` it's really easy to lose track of the hierarchy. A format button would establish the levels for you quite easily.

2. Remove the right "Visual editor". It gets in the way really and isn't helpful at least to me. I don't think this is something that we can change someone's mind about. It's one of the things where "I just don't like it" is a good argument. Maybe we need to vote. Also, now when you remove it, the ace-editor doesn't know the window has resized, so it keeps wrapping the code early (before reaching full width). You need to resize the whole window to trigger recalcuation. 

3. Consider forking [Stackbitz](https://stackblitz.com/edit/js-hta7xj). It looks way better and people are quite used to VS Code. Imagine this beauty. I would love to take on this task. It will cover 1 and 2 and gives us a free established UX built by Microsoft.
![image](https://user-images.githubusercontent.com/17054134/46142778-57c15a00-c258-11e8-9921-3aa63dbd65c9.png) 

4. Activite current highlighting mechanism on hover, so I don't have to click on the selector combo-box item to to see if that's the composition I want after it's highlighted. By highlighting I mean the dark overlay that is added by juicy-highlight. I suggest activiting that on hover of the drop down item.

5. Maybe serve composition editor from a different host. To have the ability to zoom in/out without zooming in and out the app itself. Now since they're the same host, you can't zoom one without the other affected. I think wrapping everything in iframe and injecting the iframe in the popup without giving it a URL (like we do now) would do.

6. <kbd>Close</kbd> button now acts like <kbd>Cancel</kbd>. It discards the interim changes creating the need to refresh to see them.

7. If the state is dirty (unsaved changes). Confirm before closing. Especially using the escape key.

8. Put restore default button a little further from Save. It too easy to lose your work due to proximity and similiarity of color with Save. Reset and cancel should be put on right together.

9. Even though [the vote is very close](https://starcounter.slack.com/archives/C5Q4Y78F5/p1538045471000100), I still think the composition editor should open in a new full window and used on another screen. Doesn't matter if this window is a popup or tab.

**Comment by warpech** [comment]
Thanks a lot for so many observations!

Such a long list is not very workable. We should turn this into separate issues and implement the ideas we agree with in separate PRs.

That said, few ideas of my own:

10. The button "Restore default" restores the default compositions defined in the view HTML files. If there also is a default parent composition (see: Blendable menus in UniformDocs), there is no way to restore to it.

11. There should be a way to peek into the source code of the default composition without restoring to it.

12. There should be a way to find empty `<slot>`s and slotable elements that are not slotted. This will help to manage the custom compositions after changes in the view HTMLs.

**Comment by alshakero** [comment]
All moved to seperate issues except 

> The button "Restore default" restores the default compositions defined in the view HTML files. If there also is a default parent composition (see: Blendable menus in UniformDocs), there is no way to restore to it.

Because I don't understand it to rephrase it. Could you please create an issue with it?

I'll close this one.

**Comment by warpech** [comment]
> Could you please create an issue with it?

Done: https://github.com/Starcounter/starcounter-layout-html-editor/issues/56
