### ISSUE TITLE
Create GUI controls for the tree-view

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-layout-html-editor#5]
As we are implementing WYSIWYG editor we need few simple, but good-looking controls for basic operations for selected element/-s:
 - move up & down - within parent node
 - hide/show 
 - resize - set just the width to specific value
 - create a group/container/folder - to create an empty div
 - move up & down in DOM tree - inside and outside from parent container

There is already a branch with separated editor https://github.com/Starcounter/starcounter-layout-html-editor/blob/visual-editor/juicy-simple-visual-html-editor.html as I plan to move it to the Juicy org

**Comment by tomalec** [comment]
//cc @alshakero

**Comment by alshakero** [comment]
@tomalec can you assign me to it? Working on it...

**Comment by tomalec** [comment]
I've tried to but for some reason I cannot type your name into assignees :/, can you assign it to yourself?

**Comment by alshakero** [comment]
@tomalec I guess [that's because](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/)

> You can only create assignments for yourself, collaborators on personal projects, or members of your organization with read permissions on the repository. When creating assignments, you can add up to ten assignees to support your workflow.

**Comment by warpech** [comment]
I will check if this is still relevant.

**Comment by warpech** [comment]
All of the features mentioned in OP are implemented and work well. Tested in Chrome with an ad-hoc workaround for https://github.com/Juicy/juicy-dom-tree-view/issues/3
