### ISSUE TITLE
Implement simple operations for the tree-view editor

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-layout-html-editor#6]
As we are implementing WYSIWYG editor we need to be able to perform basic operations for selected element/-s:
 - move up & down - within parent node
 - hide/show 
 - resize - set just the width to specific value
 - create a group/container/folder - to create an empty div
 - move up & down in DOM tree - inside and outside from parent container

GUI work is separated to https://github.com/Starcounter/starcounter-layout-html-editor/issues/5

There is already a branch with separated editor https://github.com/Starcounter/starcounter-layout-html-editor/blob/visual-editor/juicy-simple-visual-html-editor.html as I plan to move it to the Juicy org

**Comment by warpech** [comment]
I will check if this is still relevant.

**Comment by warpech** [comment]
All of the features mentioned in OP are implemented and work well. Tested in Chrome with an ad-hoc workaround for https://github.com/Juicy/juicy-dom-tree-view/issues/3
